# Based on
  # https://github.com/allenai/open-instruct/blob/main/scripts/train/qwen/qwen3_4b_dapo_math_32k.sh
  # https://beaker.org/orgs/ai2/workspaces/oe-adapt-code/work/01KNJ0CTMABCW4NX3SCH33MMEB

name: gsm-math-qwen3.5-2b-100k
# model: Qwen/Qwen3.5-2B-Base
model: Qwen/Qwen3-4B-Base
chat_template: qwen_instruct_user_boxed_math

mix:
  - dataset: ai2-adapt-dev/rlvr_gsm8k_zs
    proportion: 1.0
    split: train

eval_mix:
  - dataset: ai2-adapt-dev/rlvr_gsm8k_zs
    num_samples: 16
    split: train

training:
  learning_rate: 1.0e-6
  beta: 0.0
  total_episodes: 1048576 # total completions (# train steps * # unique prompts * # rollouts per prompt)
  temperature: 1.0
  response_length: 32256
  max_prompt_token_length: 512
  pack_length: 32768
  num_samples_per_prompt_rollout: 16
  num_unique_prompts_rollout: 32 # num distinct prompts per train step
  async_steps: 4
  per_device_train_batch_size: 1
  kl_estimator: 2
  lr_scheduler_type: constant
  deepspeed_stage: 3
  gradient_checkpointing: true
  seed: 1
  local_eval_every: 100
  save_freq: 100
  non_stop_penalty: false
  apply_verifiable_reward: true

infra:
  num_learners_per_node: 4
  vllm_num_engines: 4
  vllm_tensor_parallel_size: 1

beaker:
  cluster: ai2/jupiter
  workspace: ai2/adaptability
  budget: ai2/oe-adapt
  num_nodes: 1
  gpus: 8
  priority: urgent
  preemptible: true
  image: michaeln/open_instruct
  setup_commands:
    - python -c "p=__import__('transformers').__file__.replace('__init__.py','modeling_rope_utils.py');t=open(p).read().replace('received_keys -= ignore_keys','received_keys -= set(ignore_keys)');open(p,'w').write(t)"
    - python -c "p=__import__('transformers').__file__.replace('__init__.py','modeling_utils.py');t=open(p).read().replace('model = cls(config, *model_args, **model_kwargs)','model_kwargs.pop(\"use_cache\", None); model = cls(config, *model_args, **model_kwargs)');open(p,'w').write(t)"
  env:
    VLLM_ALLOW_LONG_MAX_MODEL_LEN: "1"
    VLLM_ATTENTION_BACKEND: FLASH_ATTN

extra_args:
  # - --active_sampling # prioritize prompts with low, but non-zero, correctness
  - --inflight_updates
  - --vllm_enable_prefix_caching
  - --clip_higher
  - "0.272"
  - --mask_truncated_completions
  - "False"
  - --load_ref_policy
  - "True"
  - --num_mini_batches
  - "1"
  - --stop_strings
  - "</answer>"
  - --checkpoint_state_freq
  - "100"
  - --checkpoint_state_dir
  - /weka/oe-adapt-default/allennlp/deletable_checkpoint/davidh/gsm-math-qwen3.5-2b-100k
  - --wandb_project
  - rl-mixing
